config:
  team:
    overRideSpawnCommand: true
    growhealth: true
    leastexp: 24
    size: 20
    growperlevel: 2
    effectnear: 16
    skillcooldown: 90

black-world:
- world_nether
- world_the_end
